entities:
  environment:
    # 房间号
    room: 10000
    # 难度 | 1 ~ 100
    difficulty: 1
  gift:
    - condition: 'GiftName === "玫瑰" && GiftCount >= 2'
      actions:
        - action: spawn
          arguments: [ ]
    - condition: 'GiftName === "玫瑰" && GiftCount === 1'
      actions:
        - action: spawn
          arguments:
            amount: 1
            type: entity
            subType: creeper
            name: ${giverName} 的怪物
        - action: spawn
          arguments:
            amount: 1
            type: practice
            subType: creeper
        - action: delay
          arguments: [ ]
        - action: notify
          arguments: [ ]
        - action: play
          arguments:
            type: effect
            subType: ''
        - action: play
          arguments:
            type: sound
            subType: ''
        - action: play
          arguments:
            type: note
            subType: ''
        - action: execute
          arguments:
            content: 'nuke'
listeners:
  interaction:
    # 解码器地址
    fqdn: ws://127.0.0.1:8888
