entities:
  environment:
    # 房间号
    room: 10000
    # 倍率
    multiply: 1
    # 难度 | -∞ ~ +∞
    difficulty: 1.0
  gift:
    - condition: 'GiftName === "玫瑰" && GiftCount >= 2'
      actions:
        - action: spawn
          arguments:
            amount: 1
            type: entity
            subtype: CREEPER
            name: ${giver} 的怪物
    - condition: 'GiftName === "玫瑰" && GiftCount === 1'
      actions:
        - action: spawn
          arguments:
            amount: 1
            type: entity
            subtype: CREEPER
            name: ${giver} 的怪物
        - action: spawn
          arguments:
            amount: 6
            type: practice
            subtype: EXPLOSION_HUGE
        - action: delay
          arguments:
            # 毫秒
            period: 2048
        - action: spawn
          arguments:
            amount: 3
            type: entity
            subtype: PRIMED_TNT
        - action: notify
          arguments:
            # Tick
            stay: 70
            fadeIn: 10
            fadeOut: 20
            type: title
            title: '§eA title'
            subtitle: '§aA subtitle.'
        - action: play
          arguments:
            type: effect
            subtype: DRAGON_BREATH
        - action: play
          arguments:
            type: sound
            subtype: AMBIENT_CAVE
            pitch: 100.0
            volume: 100.0
        - action: play
          arguments:
            type: music
            subtype: 'F:\resources\backgroundMusic.mp3'
        - action: execute
          arguments:
            content: 'weather clear'
        - action: execute
          arguments:
            content: 'time set 0'
        - action: input
          arguments:
            type: keyPress
            subtype: VK_W
        - action: delay
          arguments:
            period: 2048
        - action: input
          arguments:
            type: keyPress
            subtype: VK_E
        - action: input
          arguments:
            type: keyRelease
            subtype: VK_W
        - action: delay
          arguments:
            period: 2048
        - action: input
          arguments:
            type: keyRelease
            subtype: VK_E
        - action: input
          arguments:
            type: mousePress
            subtype: BUTTON1_DOWN_MASK
        - action: delay
          arguments:
            period: 2048
        - action: input
          arguments:
            type: mouseRelease
            subtype: BUTTON1_DOWN_MASK
        - action: input
          arguments:
            type: mouseMove
            # 移动到具体坐标点 | [x, y]
            offset: [1024, 2048]
        - action: input
          arguments:
            type: mouseMove
            # 根据当前鼠标位置偏移 | [x + 1024, y + 0]
            offset: [+1024, +0]
listeners:
  interaction:
    # 解码器地址
    fqdn: ws://127.0.0.1:8888
